{
  description = "slope — structural code review for large LLM-written changes";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay.url = "github:oxalica/rust-overlay";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      nixpkgs,
      rust-overlay,
      flake-utils,
      ...
    }:
    # No x86_64-darwin: nixpkgs-unstable dropped it outright in 26.11, so an
    # Intel Mac cannot evaluate this flake against that input at all.
    flake-utils.lib.eachSystem [
      "x86_64-linux"
      "aarch64-darwin"
    ] (
      system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ (import rust-overlay) ];
        };
        inherit (pkgs) lib;
        llvmPackages = pkgs.llvmPackages_latest;
        # Keep this exact nightly aligned with both Rust install steps in CI.
        rustToolchain = pkgs.rust-bin.nightly."2026-05-17".default.override {
          extensions = [
            "rust-src"
            "rust-analyzer"
            "clippy"
            "llvm-tools-preview"
          ];
          # Dioxus web builds compile the client to wasm.
          targets = [ "wasm32-unknown-unknown" ];
        };

        # `dx` drives three external tools to build the web client. It normally
        # downloads them itself, which the build sandbox has no network for (and
        # whose binaries don't run on NixOS anyway), so they are pinned here and
        # `dx` is pointed at them via NO_DOWNLOADS.
        dxToolchain = [
          pkgs.dioxus-cli
          # Must match the pinned wasm-bindgen crate in Cargo.toml exactly.
          pkgs.wasm-bindgen-cli_0_2_126
          pkgs.binaryen
          # Standalone Tailwind v4 CLI; `dx` autodetects and drives it.
          pkgs.tailwindcss_4
        ];

        # Only the files a build actually reads. An allowlist rather than a
        # deny-list because `target/` here is tens of gigabytes — a stray
        # `./.` would copy all of it into the store.
        source = lib.fileset.toSource {
          root = ./.;
          fileset = lib.fileset.unions [
            ./Cargo.toml
            ./Cargo.lock
            ./Dioxus.toml
            ./clippy.toml
            ./tailwind.css
            ./README.md
            ./LICENSE-MIT
            ./LICENSE-APACHE
            ./src
            # `assets/tailwind.css` is generated by the Tailwind pass during the
            # build. Keeping a locally generated copy out of the source keeps
            # the derivation independent of whatever is on this machine.
            (lib.fileset.difference ./assets (lib.fileset.maybeMissing ./assets/tailwind.css))
          ];
        };

        slope = pkgs.stdenv.mkDerivation {
          pname = "slope";
          version = "0.1.0";
          src = source;

          # Every dependency resolves from crates.io, so the lockfile's own
          # checksums are the whole story — no per-git-dep output hash to keep
          # in step with a rev.
          cargoDeps = pkgs.rustPlatform.importCargoLock { lockFile = ./Cargo.lock; };

          nativeBuildInputs = [
            pkgs.rustPlatform.cargoSetupHook
            rustToolchain
            pkgs.pkg-config
            pkgs.makeWrapper
          ]
          ++ dxToolchain;

          # Resolve tailwindcss/wasm-bindgen/wasm-opt from PATH instead of
          # fetching binaries the sandbox has no network for (and which would
          # not run here on NixOS regardless).
          NO_DOWNLOADS = "1";

          buildPhase = ''
            runHook preBuild

            # `dx` and the Tailwind CLI both want a writable home for caches.
            export HOME=$(mktemp -d)

            # `dx bundle` defaults to a debug build, which yields a ~110MB wasm
            # client. `--release` is what makes this a distributable bundle, and
            # dropping the wasm DWARF section takes it down another order of
            # magnitude — a shipped bundle is not what anyone debugs.
            dx bundle --platform web --release --debug-symbols false \
              --out-dir "$PWD/bundle"

            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall

            # The bundle is a `server` binary beside a `public/` directory of
            # hashed client assets. `dx` picks the exact nesting itself, so find
            # the binary rather than hard-coding a layout that may shift.
            server=$(find bundle -type f -name server -perm -u+x | head -1)
            if [ -z "$server" ]; then
              echo "no server binary in the dx bundle:" >&2
              find bundle -maxdepth 3 >&2
              exit 1
            fi

            mkdir -p $out/libexec/slope
            cp -r "$(dirname "$server")"/. $out/libexec/slope/

            # slope shells out to `cargo metadata` and to git/jj for the diff.
            # Suffix, not prefix: a workspace's own toolchain must win, since
            # the code survey has to agree with how that workspace builds.
            makeWrapper $out/libexec/slope/server $out/bin/slope \
              --set DIOXUS_PUBLIC_PATH $out/libexec/slope/public \
              --suffix PATH : ${
                lib.makeBinPath [
                  pkgs.cargo
                  pkgs.git
                ]
              }

            runHook postInstall
          '';

          meta = {
            description = "Structural code review for large LLM-written changes to a cargo workspace";
            homepage = "https://github.com/XiangpengHao/slope";
            license = with lib.licenses; [
              mit
              asl20
            ];
            mainProgram = "slope";
            platforms = [ system ];
          };
        };
      in
      {
        packages = {
          default = slope;
          inherit slope;
        };

        apps.default = {
          type = "app";
          program = "${slope}/bin/slope";
          meta.description = "Serve the slope chart for the cargo workspace in the working directory";
        };

        devShells.default = pkgs.mkShell {
          packages = [
            rustToolchain
            pkgs.pkg-config
            pkgs.cargo-fuzz
            llvmPackages.llvm
            pkgs.cargo-binutils
          ]
          ++ dxToolchain;

          ASAN_SYMBOLIZER_PATH = "${llvmPackages.llvm}/bin/llvm-symbolizer";

          # Prebuilt binaries `dx` fetches don't run on NixOS, and pinning them
          # keeps every platform on the same versions; make `dx` resolve
          # tailwindcss/wasm-bindgen/wasm-opt from PATH instead.
          NO_DOWNLOADS = "1";
        };
      }
    );
}
