use dioxus::prelude::*;

mod components;
mod views;

use views::{Home, Navbar};

/// Internal routes. Each variant maps to a URL pattern; matching a pattern
/// renders the component named by the variant.
#[derive(Debug, Clone, Routable, PartialEq)]
#[rustfmt::skip]
enum Route {
    // `layout` wraps every route beneath it in a shared component.
    #[layout(Navbar)]
        #[route("/")]
        Home {},
}

// `asset!` paths are relative to the crate root. The macro hashes and rewrites
// the path at build time so assets are content-addressed in the final bundle.
const FAVICON: Asset = asset!("/assets/favicon.ico");
// Generated by the tailwindcss watcher that `dx serve` starts for us.
const TAILWIND_CSS: Asset = asset!("/assets/tailwind.css");

fn main() {
    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    rsx! {
        document::Link { rel: "icon", href: FAVICON }
        document::Stylesheet { href: TAILWIND_CSS }

        Router::<Route> {}
    }
}
